FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY package.json ./
ENV REPORTS_DIR=/data/reports
RUN mkdir -p /data/reports
EXPOSE 3005
CMD ["node", "dist/index.js"]
